GET http://localhost:5000/users

###
GET http://localhost:5000/users/2

###
POST http://localhost:5000/users
Content-Type: application/json

{
    "name": "Rai Paramartha",
    "email": "rai@gmail.com",
    "gender": "Male"
}

###
PATCH http://localhost:5000/users/1
Content-Type: application/json

{
    "name": "M Fikri",
    "email": "mfikri@gmail.com",
    "gender": "Male"
}

###
DELETE http://localhost:5000/users/2

###

GET http://localhost:5000/posts
Content-Type: application/json


###

POST http://localhost:5000/posts
Content-Type: application/json

{
    "post": "i luv jes",
    "user_id": 2,
    "likes": 0
}

###

GET http://localhost:5000/postsWithName
Content-Type: application/json


###